language: c
compiler:
  - clang
  - gcc
env:
  - memcheck=yes
  - memcheck=no
before_install: sudo apt-get install -y libcairo2-dev libpango1.0-dev valgrind
install: sudo make install
script: make test
