language: c
compiler:
  - clang
  - gcc
env:
  - memcheck=yes optimize=yes
  - memcheck=yes optimize=no
  - memcheck=no optimize=yes
  - memcheck=no optimize=no
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libcairo2-dev libpango1.0-dev valgrind
  - wget http://genometools.org/pub/genometools-unstable.tar.gz
  - tar xzf genometools-unstable.tar.gz
  - cd genometools-unstable && sudo make 64bit=yes install && cd -
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/genometools-x86_64.conf'
  - sudo ldconfig
install: sudo make install
script: make test
