language: c
compiler:
  - clang
  - gcc
env:
  - memcheck=yes optimize=yes
  - memcheck=yes optimize=no
  - memcheck=no optimize=yes
  - memcheck=no optimize=no
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libcairo2-dev libpango1.0-dev valgrind
  - wget http://genometools.org/pub/binary_distributions/gt-1.5.3-Linux_x86_64-64bit-complete.tar.gz
  - tar xzf gt-1.5.3-Linux_x86_64-64bit-complete.tar.gz
  - sudo cp -r gt-1.5.3-Linux_x86_64-64bit-complete/bin/* /usr/local/bin/
  - sudo cp -r gt-1.5.3-Linux_x86_64-64bit-complete/include/genometools /usr/local/include/
  - sudo cp -r gt-1.5.3-Linux_x86_64-64bit-complete/lib/* /usr/local/lib/
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/genometools-x86_64.conf'
  - sudo ldconfig
install: sudo make install
script: make test
