language: c
compiler:
  - clang
  - gcc
env:
  matrix:
    - memcheck=yes optimize=yes
    - memcheck=yes optimize=no
    - memcheck=no optimize=yes
    - memcheck=no optimize=no
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libcairo2-dev libpango1.0-dev valgrind
  - wget http://genometools.org/pub/binary_distributions/gt-1.5.8-Linux_x86_64-64bit-complete.tar.gz
  - tar xzf gt-1.5.8-Linux_x86_64-64bit-complete.tar.gz
  - sudo cp -r gt-1.5.8-Linux_x86_64-64bit-complete/bin/* /usr/local/bin/
  - sudo cp -r gt-1.5.8-Linux_x86_64-64bit-complete/include/genometools /usr/local/include/
  - sudo cp -r gt-1.5.8-Linux_x86_64-64bit-complete/lib/* /usr/local/lib/
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/genometools-x86_64.conf'
  - sudo ldconfig
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - clang
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - sudo make install
  - sudo ldconfig
script: make test
