language: c
compiler:
  - clang
  - gcc
env:
  - memcheck=yes
  - memcheck=no
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libcairo2-dev libpango1.0-dev valgrind
  - bash data/scripts/gt-install-travis.sh
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/aegean-x86_64.conf'
  - sudo ldconfig
install: sudo make install
script: make test
