#!/usr/bin/env python
import re, sys

# Usage: tidy < in.gff3 > out.gff3

transtypes = { "mRNA":1, "tRNA":1, "rRNA":1, "ncRNA":1 }
pseudogenefixes = {}
transfixes = {}

for line in sys.stdin:
  line = line.rstrip()
  if line == "" or line.startswith("#"):
    print line
    continue

  values = line.split("\t")
  ftype = values[2]
  region = "%s:%s-%s" % (values[0], values[3], values[4])

  if ftype == "gene" and line.count("pseudo=true") > 0:
    line = line.replace("\tgene\t", "\tpseudogene\t")
    values[2] = "pseudogene"
    ftype = "pseudogene"
    pseudogenefixes[region] = 1

  m = re.search("Parent=([^;\n]+)", values[8])
  if not m and ftype in transtypes:
    if not ftype in transfixes:
      transfixes[ftype] = {}
    transfixes[ftype][region] = 1

    parentid = "%s:gene" % region
    if values[8] != "":
      line += ";"
    line += "Parent=%s" % parentid
    parentgff3 = "%s\ttidy\tgene\t%s\t%s\t.\t%s\t.\tID=%s" % (values[0], values[3], values[4], values[6], parentid)
    print parentgff3

  print line

print >> sys.stderr, "===== Fixes ====="
print >> sys.stderr, "  gene --> pseudogene: %lu" % len(pseudogenefixes.keys())
for ftype in transfixes.keys():
  print >> sys.stderr, "  %s parent: %lu" % (ftype, len(transfixes[ftype].keys()))
